#cloud-config
packages:
  - curl
  - ifupdown
package_update: true
package_upgrade: true
users:
  - name: cluster
    ssh-authorized-keys:
      - ssh-rsa AAAA[LOCALHOST_SSH_PUBLIC_KEY] 
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
runcmd:
  - |
    cat <<'EOF' >> /etc/network/interfaces
    auto eth0
    iface eth0 inet dhcp
        post-up echo 1 > /proc/sys/net/ipv4/ip_forward
        post-up iptables -t nat -A POSTROUTING -s '10.0.0.0/16' -o eth0 -j MASQUERADE
    EOF
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
  - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - runuser -l cluster -c 'mkdir -p ~/.kube'
  - reboot
